### ISSUE TITLE
Bantu fix file /prototype/reservasi/layouts/partials/navbar.php

### ISSUE THREAD

**Issue by kakekcoding** [kakekcoding/prototype#3]
Bantu fix file /prototype/reservasi/layouts/partials/navbar.php
@nurohman-fitriyanto

**Comment by idigitouch** [comment]
http://blog.fofwebdesign.co.uk/40-highlight-the-menu-button-for-the-current-web-page cuy

**Comment by kakekcoding** [comment]
Weh nganggo js?

**Comment by idigitouch** [comment]
work perfectly http://fofwebdesign.co.uk/template/_testing/highlight-current-menu/index.htm
